# Generated by Django 4.1.4 on 2023-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shikuchoson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='version')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='create time')),
                ('creator', models.CharField(blank=True, max_length=120, null=True, verbose_name='creator')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('updater', models.CharField(blank=True, max_length=120, null=True, verbose_name='updater')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='valid')),
                ('shikuchoson_code', models.CharField(max_length=5, unique=True, verbose_name='shikuchoson_code')),
                ('todofuken_name', models.CharField(max_length=8, verbose_name='todofuken_name')),
                ('shikuchoson_name', models.CharField(max_length=24, verbose_name='shikuchoson_name')),
                ('todofuken_kana', models.CharField(max_length=8, verbose_name='todofuken_kana')),
                ('shikuchoson_kana', models.CharField(max_length=24, verbose_name='shikuchoson_kana')),
            ],
            options={
                'verbose_name': 'shikuchoson',
                'verbose_name_plural': 'shikuchoson',
                'ordering': ['shikuchoson_code'],
                'default_permissions': [],
                'unique_together': {('shikuchoson_code',)},
            },
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='version')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='create time')),
                ('creator', models.CharField(blank=True, max_length=120, null=True, verbose_name='creator')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('updater', models.CharField(blank=True, max_length=120, null=True, verbose_name='updater')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='valid')),
                ('shikuchoson_code', models.CharField(max_length=5, verbose_name='shikuchoson_code')),
                ('old_postcode', models.CharField(blank=True, max_length=5, null=True, verbose_name='old_postcode')),
                ('postcode', models.CharField(blank=True, max_length=7, null=True, verbose_name='postcode')),
                ('todofuken_kana', models.CharField(max_length=8, verbose_name='todofuken_kana')),
                ('shikuchoson_kana', models.CharField(max_length=24, verbose_name='shikuchoson_kana')),
                ('choiki_kana', models.CharField(max_length=500, verbose_name='choiki_kana')),
                ('todofuken_name', models.CharField(max_length=8, verbose_name='todofuken_name')),
                ('shikuchoson_name', models.CharField(max_length=24, verbose_name='shikuchoson_name')),
                ('choiki_name', models.CharField(max_length=500, verbose_name='choiki_name')),
                ('multiple_postcode_flag', models.IntegerField(blank=True, choices=[(1, 'On'), (0, 'Off')], default=0, null=True, verbose_name='multiple_postcode_flag')),
                ('banchi_overlap_flag', models.IntegerField(blank=True, choices=[(1, 'On'), (0, 'Off')], default=0, null=True, verbose_name='banchi_overlap_flag')),
                ('has_chome_flag', models.IntegerField(blank=True, choices=[(1, 'On'), (0, 'Off')], default=0, null=True, verbose_name='has_chome_flag')),
                ('multiple_choiki_flag', models.IntegerField(blank=True, choices=[(1, 'On'), (0, 'Off')], default=0, null=True, verbose_name='multiple_choiki_flag')),
                ('change_type', models.IntegerField(blank=True, choices=[(0, '変更なし'), (1, '変更あり'), (2, '廃止')], default=0, null=True, verbose_name='change_type')),
                ('change_reason', models.IntegerField(blank=True, default=0, null=True, verbose_name='change_reason')),
            ],
            options={
                'verbose_name': 'postcode',
                'verbose_name_plural': 'postcodes',
                'ordering': ['postcode', 'choiki_kana'],
                'default_permissions': [],
                'unique_together': {('shikuchoson_code', 'postcode', 'choiki_name')},
            },
        ),
    ]
